# Example GitHub Actions workflow for CI/CD with integrated testing
# This file demonstrates how to set up automated deployment and testing
# Copy this to .github/workflows/deploy.yml to use it

name: Deploy and Test Databricks Bundle

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  validate:
    name: Validate Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle configuration
        run: databricks bundle validate

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy to Dev
        run: databricks bundle deploy --target dev

      - name: Run Main Workflow
        run: databricks bundle run demo_workflow --target dev

      - name: Run Integration Tests
        run: databricks bundle run integration_tests --target dev

      - name: Report Test Results
        if: always()
        run: echo "Integration tests completed. Check Databricks workspace for detailed results."

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy to Production
        run: databricks bundle deploy --target prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}

      - name: Run Main Workflow
        run: databricks bundle run demo_workflow --target prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}

      - name: Run Integration Tests
        run: databricks bundle run integration_tests --target prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}

      - name: Report Test Results
        if: always()
        run: echo "Production integration tests completed. Check Databricks workspace for detailed results."

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Deployment or tests failed in production!"
          # Add notification logic here (Slack, email, etc.)

